version: '3.9'

services:
  file-sorter-app:
    build:
      context: ./../src/
      dockerfile: FileSorter.App/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - SortOptions__WorkFolderPath=workFolder
    volumes:
      - type: bind
        source: ../_workFolder
        target: /app/workFolder
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 4096M
        reservations:
          cpus: "6"
          memory: 1024M
    restart: "no"
        
#  file-generator-app:
#    build:
#      context: ./../
#      dockerfile: ../src/FileGenerator.App/Dockerfile
#    environment:
#      - DOTNET_ENVIRONMENT=Development
#      - SortOptions__WorkFolderPath=_workFolder
#    volumes:
#      - ./_workFolder:_workFolder
#    restart: none